common/models/Tool.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Tool as BaseTool;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tool".
 */
class Tool extends BaseTool
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                ],
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                  # custom validation rules
             ]
        );
    }

    public static function items($mode = '') {
        $where = '';

        if ($mode == 'onmain') {
            $where = ['onmain' => 1];
        }

        return Tool::find()
            ->orderBy(['order' => SORT_ASC])
            ->where($where)
            ->all();
    }
}

backend/controllers/BrifController.php
<?php

namespace backend\controllers;

use common\models\Brif;

/**
* This is the class for controller "BrifController".
*/
class BrifController extends \backend\controllers\base\BrifController
{
    public function actionCreate()
    {
        $model = new Brif;

        try {
            if ($model->load($_POST) && $model->save()) {
                if ($_POST['mode'] == 'justSave') {
                    return $this->redirect(['update', 'id' => $model->id]);
                } else {
                    return $this->redirect(['index', 'id' => $model->id]);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Brif model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            if ($_POST['mode'] == 'justSave') {
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                return $this->redirect(['index', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

backend/controllers/ToolController.php
<?php

namespace backend\controllers;

use common\models\Tool;

/**
* This is the class for controller "ToolController".
*/
class ToolController extends \backend\controllers\base\ToolController
{
    public function actionCreate()
    {
        $model = new Tool;

        try {
            if ($model->load($_POST) && $model->save()) {
                if ($_POST['mode'] == 'justSave') {
                    return $this->redirect(['update', 'id' => $model->id]);
                } else {
                    return $this->redirect(['index', 'id' => $model->id]);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Tool model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            if ($_POST['mode'] == 'justSave') {
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                return $this->redirect(['index', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

frontend/controllers/ToolController.php
<?php
namespace frontend\controllers;

use common\models\Tool;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class ToolController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView($alias)
    {
        $model = Tool::find()->where(['alias' => $alias])->one();

        if (!$model) {
            throw new NotFoundHttpException();
        }

        return $this->render('view', [
            'model' => $model
        ]);
    }
}

frontend/views/tool/_item.php
<?php 
use yii\helpers\Url;
?>
<div class="tools__item tools__item_tool" style="background-image: url(<?=$model->previewimage?>);">
    <a href="<?=Url::to(['tool/view', 'alias' => $model->alias])?>" class="tools__itemHeader"><span><?=$model->name?></span></a>
    <div class="tools__itemInfo"><?=$model->introtext?></div>
    <a href="<?=Url::to(['tool/view', 'alias' => $model->alias])?>" class="tools__itemButton"></a>
</div>

frontend/views/tool/index.php
<?php
use common\models\Tool;

$this->params['seotitle'] = 'seotitle';
$this->params['seodescription'] = 'seodescription';
$this->params['seokeywords'] = 'seokeywords';
$this->params['seoh1'] = 'Инструменты';
?>
<div class="contentWithImage">
    <div class="container">
        <div class="contentWithImage__inner">
            <div class="contentWithImage__left">
                <img src="/img/cimage.png" alt="">
            </div>
            <div class="contentWithImage__right">
                <h1 class="header withLine"><?=$this->params['seoh1']?> <span></span></h1>
                <p>Иногда мы публикуем некоторые важные вещи, например, как часто нужно кормить котиков или как общаться с очень назойливым клиентом, если деньги оплачены работа сделана, а акты подписывать отказываются. На самом деле, опыта и слов очень много, собрать бы их всех воедино. Подписывайтесь на наш RSS, канал.</p>
                <p>Иногда мы публикуем некоторые важные вещи, например, как часто нужно кормить котиков или как общаться с очень назойливым клиентом, если деньги оплачены работа сделана, а акты подписывать отказываются.</p>
            </div>
        </div>
    </div>
</div>

<div class="case" style="padding-top: 1px;">
    <div class="container margin">
        <?=$this->render('@frontend/views/blocks/innovate')?>
    </div>

    <div class="tools">
        <div class="container">
            <div class="tools__inner">
                <?php
                $tools = Tool::items();
                foreach($tools as $model) {
                    echo $this->render('@frontend/views/tool/_item', ['model' => $model]);
                }
                ?>
            </div>
        </div>
    </div>
</div>

frontend/views/tool/view.php
<?php

use yii\helpers\Url;

$this->params['seotitle'] = $model->seotitle;
$this->params['seodescription'] = $model->seodescription;
$this->params['seokeywords'] = $model->seokeywords;
$this->params['seoh1'] = $model->seoh1;
$this->params['name'] = $model->name;

?>
<div class="contentWithImage">
    <div class="container">
        <div class="contentWithImage__inner">
            <div class="contentWithImage__left">
                <img src="<?=$model->image?>" alt="">
            </div>
            <div class="contentWithImage__right">
                <h1 class="header withLine">
                    <?=(!empty($model->seoh1))? $model->seoh1 : $model->name?>
                    <span></span>
                </h1>
                <?=$model->content?>
                <div class="contentWithImage__buttons">
                    <a href="<?=Url::to(['brif/view', 'alias' => \common\models\Brif::findOne($model->brif_id)->alias])?>"
                       class="button3"
                       target="_blank">
                        <span class="button3__text">Бриф</span>
                        <span class="button3__s"></span>
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="<?=$model->presentation?>" class="button4 button_pres" target="_blank">
                        <span class="button4__text">Презентация</span>
                        <span class="button4__s"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<?=$model->html_digits?>

<div class="toolBlock">
    <div class="container">
        <?=$model->html?>
    </div>
</div>

<?=$this->render('@frontend/views/blocks/cases')?>