common/models/Casee.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Casee as BaseCasee;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "casee".
 */
class Casee extends BaseCasee
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                ],
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                  # custom validation rules
             ]
        );
    }
}

backend/controllers/CaseeController.php
<?php

namespace backend\controllers;

use common\models\Casee;
use yii\helpers\Url;

/**
* This is the class for controller "CaseeController".
*/
class CaseeController extends \backend\controllers\base\CaseeController
{
    public function actionCreate()
    {
        $model = new Casee;

        try {
            if ($model->load($_POST) && $model->save()) {
                if ($_POST['mode'] == 'justSave') {
                    return $this->redirect(['update', 'id' => $model->id]);
                } else {
                    return $this->redirect(['index', 'id' => $model->id]);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Casee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            if ($_POST['mode'] == 'justSave') {
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                return $this->redirect(['index', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

frontend/controllers/CaseeController.php
<?php
namespace frontend\controllers;

use common\models\Casee;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class CaseeController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView($alias)
    {
        $model = Casee::find()->where(['alias' => $alias])->one();
        
        if (!$model) {
            throw new NotFoundHttpException();
        }

        return $this->render('view', [
            'model' => $model
        ]);
    }
    public function actionMore()
    {
        $this->enableCsrfValidation = false;
        $casees = Casee::find()
            ->limit(9)
            ->orderBy(['order' => SORT_ASC])
            ->offset($_POST['already'])
            ->all();
        $allCaseesCount = count(Casee::find()
            ->orderBy(['order' => SORT_ASC])
            ->asArray()
            ->all()
        );
        $availableCaseesCount = count($casees) + $_POST['already'];
        $result = [];

        foreach($casees as $model) {
            $item = str_replace('"', "'", trim($this->renderPartial('@frontend/views/casee/_item', ['model' => $model])));
            $item = str_replace(array("\r", "\n", "\r\n", "\t"), "", $item);
            $result[] = $item;
        }

        return '{"items": "'.implode('', $result).'", 
            "availableCount": "'.$availableCaseesCount.'",
            "allCount": "'.$allCaseesCount.'"}';
    }
}

frontend/views/casee/_item.php
<?php 
use yii\helpers\Url;
?>
<a href="<?=Url::to(['casee/view', 'alias' => $model->alias])?>" class="catalog__item">
    <img src="<?=$model->previewimage?>" class="catalog__itemImage">
    <span class="catalog__itemHeader"><?=$model->name?></span>
    <span class="catalog__itemText"><?=$model->introtext?></span>
                    <span class="text-center" style="display: block;">
                        <span class="button3">
                            <span class="button3__text">Посетить &rarr;</span>
                            <span class="button3__s"></span>
                        </span>
                    </span>
</a>

frontend/views/casee/index.php
<?php
$this->params['seotitle'] = 'Кейсы и решения от рекламного агентства MakeTrue';
$this->params['seodescription'] = '';
$this->params['seokeywords'] = '';
$this->params['seoh1'] = 'Кейсы и решения';
?>

<!--<div class="contentWithImage toolBlock">
    <div class="container">
        <div class="contentWithImage__inner">
            <div class="contentWithImage__left">
                <img src="/img/cimage.png" alt="">
            </div>
            <div class="contentWithImage__right">
                <h1 class="header withLine"><?=$this->params['seoh1']?> <span></span></h1>
                <p>Иногда мы публикуем некоторые важные вещи, например, как часто нужно кормить котиков или как общаться с очень назойливым клиентом, если деньги оплачены работа сделана, а акты подписывать отказываются. На самом деле, опыта и слов очень много, собрать бы их всех воедино. Подписывайтесь на наш RSS, канал.</p>
                <p>Иногда мы публикуем некоторые важные вещи, например, как часто нужно кормить котиков или как общаться с очень назойливым клиентом, если деньги оплачены работа сделана, а акты подписывать отказываются.</p>
            </div>
        </div>
    </div>
</div>-->

<div class="cases_margin">&nbsp;
</div>

<?=$this->render('@frontend/views/blocks/cases')?>

frontend/views/casee/view.php
<?php

use yii\helpers\Url;

$this->params['seotitle'] = $model->seotitle;
$this->params['seodescription'] = $model->seodescription;
$this->params['seokeywords'] = $model->seokeywords;
$this->params['seoh1'] = $model->seoh1;
$this->params['name'] = $model->name;

?>
<div class="contentWithImage without-padding-bottom">
    <div class="container">
        <div class="contentWithImage__inner">
            <!--<div class="contentWithImage__left">
                <img src="<?=$model->image?>" alt="">
            </div>-->
            <div class="contentWithImage__right margin-left-null">
                <h1 class="header withLine">
                    <?=(!empty($model->seoh1))? $model->seoh1 : $model->name?>
                    <span></span>
                </h1>
                <?=$model->content?>
            </div>
        </div>
    </div>
</div>
<div class="case">
    <div class="container">
        <div class="case__inner">
            <div class="case__left">
                <?php if (!empty($model->inimage1)) { ?>
                    <div class="case__image">
                        <img src="<?=$model->inimage1?>" alt="">
                    </div>
                <?php } ?>
                <?php if (!empty($model->inimage2)) { ?>
                    <div class="case__image">
                        <img src="<?=$model->inimage2?>" alt="">
                    </div>
                <?php } ?>
            </div>
            <div class="case__right">
                <?php if (!empty($model->task)) { ?>
                    <div class="case__part">
                        <div class="header withLine">Задача <span></span></div>
                        <div class="case__partContent content"><?=$model->task?></div>
                    </div>
                <?php } ?>
                <?php if (!empty($model->solution)) { ?>
                    <div class="case__part">
                        <div class="header withLine">Решение <span></span></div>
                        <div class="case__partContent content"><?=$model->solution?></div>
                    </div>
                <?php } ?>
                <?php if (!empty($model->analitics)) { ?>
                    <div class="case__part">
                        <div class="header withLine">Аналитика <span></span></div>
                        <div class="case__partContent content"><?=$model->analitics?></div>
                    </div>
                <?php } ?>
                <?php if (!empty($model->icons)) { ?>
                    <div class="case__part">
                        <div class="case__icons">
                            <?=$model->icons?>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
        <?php if (!empty($model->header2) && !empty($model->content2)) { ?>
            <div class="content margin">
                <div class="header withLine"><?=$model->header2?> <span></span></div>
                <?=$model->content2?>
            </div>
        <?php } ?>
        <a href="<?=Url::to(['casee/index'])?>" class="button3">
            <span class="button3__text">Назад</span>
            <span class="button3__s"></span>
        </a>
    </div>
</div>